---
- name: "Populate service facts."
  ansible.builtin.service_facts:
  when: "'nut-driver' in nut_services"

- name: "Initialize per-driver service list."
  ansible.builtin.set_fact:
    nut_driver_services: []

- name: "Populate per-driver service list."
  ansible.builtin.set_fact:
    nut_driver_services: "{{ nut_driver_services + [service_name] if service_name in ansible_facts.services else nut_driver_services }}"
  vars:
    service_name: "nut-driver@{{ item.name }}.service"
  loop: "{{ nut_ups }}"
  when: "'services' in ansible_facts"

- name: "Restart per-driver services."
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ nut_driver_services }}"
  when: "nut_driver_services | length > 0"

# Errors are ignored here because `nut-driver` is an old service
# no more present in recent distros but it is is present by default
# inside `nut_services` because of legacy reasons
- name: "Restart bare nut-driver."
  ansible.builtin.service:
    name: nut-driver
    state: restarted
  when: "'nut-driver' in nut_services"
  ignore_errors: true

- name: "Restart other nut services."
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items: "{{ nut_services | difference(['nut-driver']) }}"
  when: nut_enable_service
